theme = "gruvbox_dark_hard"

[editor]
true-color = true

[editor.whitespace.render]
space = "all"
newline = "all"
tab = "all"

[editor.whitespace.characters]
tab = ">"
tabpad = "—"
nbsp = "⍽"
newline = "⏎"
space = "·"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
A-L = ":format"
C-A-left = "jump_backward"
C-A-right = "jump_forward"
C-b = "goto_definition"
C-d = ["extend_line_below", "yank_joined_to_clipboard", "paste_clipboard_after", "goto_line_start"]
C-s = [":w"]
"C-/" = "toggle_comments"
tab = "indent"
S-tab = "unindent"

[keys.insert]
C-s = ["normal_mode", ":w"]
"C-/" = "toggle_comments"
