theme = "gruvbox_dark_hard"

[editor.whitespace.render]
space = "all"
newline = "all"
tab = "all"

[editor.whitespace.characters]
tab = ">"
tabpad = "—"
nbsp = "⍽"
newline = "⏎"
space = "·"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1
